package server

import (
	"fmt"
	"strings"

	"github.com/jelmersnoeck/forge/internal/engine"
	"github.com/jelmersnoeck/forge/internal/review"
)

// FormatPRBody builds a structured pull request body from a build result.
// It includes the plan summary, principles applied, a findings table, and
// the iteration count.
func FormatPRBody(result *engine.BuildResult) string {
	var b strings.Builder

	b.WriteString("## Forge Governed Build\n\n")

	// Plan summary.
	if result.Plan != "" {
		b.WriteString("### Plan\n\n")
		// Truncate long plans for the PR body.
		plan := result.Plan
		if len(plan) > 2000 {
			plan = plan[:2000] + "\n\n_...plan truncated..._"
		}
		b.WriteString(plan)
		b.WriteString("\n\n")
	}

	// Iteration count.
	b.WriteString(fmt.Sprintf("### Build Summary\n\n"))
	b.WriteString(fmt.Sprintf("- **Status:** %s\n", result.Status))
	b.WriteString(fmt.Sprintf("- **Iterations:** %d\n", result.Iterations))
	b.WriteString("\n")

	// Principles covered across all reviews.
	allPrinciples := collectPrinciples(result.Reviews)
	if len(allPrinciples) > 0 {
		b.WriteString("### Principles Applied\n\n")
		for _, p := range allPrinciples {
			b.WriteString(fmt.Sprintf("- `%s`\n", p))
		}
		b.WriteString("\n")
	}

	// Findings table from the final review.
	if len(result.Reviews) > 0 {
		lastReview := result.Reviews[len(result.Reviews)-1]
		if len(lastReview.Findings) > 0 {
			b.WriteString("### Final Review Findings\n\n")
			b.WriteString("| Severity | File | Line | Principle | Message |\n")
			b.WriteString("|----------|------|------|-----------|---------|\n")
			for _, f := range lastReview.Findings {
				file := f.File
				if file == "" {
					file = "-"
				}
				line := "-"
				if f.Line > 0 {
					line = fmt.Sprintf("%d", f.Line)
				}
				pid := f.PrincipleID
				if pid == "" {
					pid = "-"
				}
				// Escape pipe characters in messages for the Markdown table.
				msg := strings.ReplaceAll(f.Message, "|", "\\|")
				b.WriteString(fmt.Sprintf("| %s | %s | %s | %s | %s |\n",
					f.Severity, file, line, pid, msg))
			}
			b.WriteString("\n")
		} else {
			b.WriteString("### Review\n\nNo findings in final review.\n\n")
		}
	}

	b.WriteString("---\n_Generated by [Forge](https://github.com/jelmersnoeck/forge) governed build_\n")

	return b.String()
}

// collectPrinciples gathers unique principle IDs from all review iterations.
func collectPrinciples(reviews []review.Result) []string {
	seen := make(map[string]bool)
	var result []string
	for _, r := range reviews {
		for _, p := range r.PrinciplesCovered {
			if !seen[p] {
				seen[p] = true
				result = append(result, p)
			}
		}
	}
	return result
}
