package server

import (
	"strings"
	"testing"

	"github.com/jelmersnoeck/forge/internal/engine"
	"github.com/jelmersnoeck/forge/internal/principles"
	"github.com/jelmersnoeck/forge/internal/review"
)

func TestFormatPRBody_FullResult(t *testing.T) {
	result := &engine.BuildResult{
		Plan:       "1. Create new handler\n2. Add tests\n3. Update docs",
		Status:     engine.BuildStatusSuccess,
		Iterations: 2,
		Reviews: []review.Result{
			{
				Findings: []review.Finding{
					{
						File:        "server.go",
						Line:        42,
						PrincipleID: "sec-001",
						Severity:    principles.SeverityCritical,
						Message:     "Missing input validation",
						Suggestion:  "Add validation",
					},
				},
				HasCritical:       true,
				PrinciplesCovered: []string{"sec-001"},
			},
			{
				Findings:          nil,
				HasCritical:       false,
				PrinciplesCovered: []string{},
			},
		},
	}

	body := FormatPRBody(result)

	// Check key sections are present.
	checks := []string{
		"## Forge Governed Build",
		"### Plan",
		"Create new handler",
		"### Build Summary",
		"**Status:** success",
		"**Iterations:** 2",
		"### Principles Applied",
		"`sec-001`",
		"### Review",
		"No findings in final review",
		"Generated by [Forge]",
	}

	for _, check := range checks {
		if !strings.Contains(body, check) {
			t.Errorf("expected PR body to contain %q, body:\n%s", check, body)
		}
	}
}

func TestFormatPRBody_WithFindings(t *testing.T) {
	result := &engine.BuildResult{
		Plan:       "Short plan",
		Status:     engine.BuildStatusMaxLoops,
		Iterations: 3,
		Reviews: []review.Result{
			{
				Findings: []review.Finding{
					{
						File:        "api.go",
						Line:        10,
						PrincipleID: "sec-002",
						Severity:    principles.SeverityWarning,
						Message:     "Missing rate limiting",
					},
				},
				HasCritical:       false,
				PrinciplesCovered: []string{"sec-002"},
			},
		},
	}

	body := FormatPRBody(result)

	if !strings.Contains(body, "| warning | api.go | 10 | sec-002 | Missing rate limiting |") {
		t.Errorf("expected findings table row in body:\n%s", body)
	}
}

func TestFormatPRBody_EmptyResult(t *testing.T) {
	result := &engine.BuildResult{
		Status:     engine.BuildStatusFailed,
		Iterations: 0,
	}

	body := FormatPRBody(result)

	if !strings.Contains(body, "## Forge Governed Build") {
		t.Error("expected header in empty result body")
	}
	if !strings.Contains(body, "**Status:** failed") {
		t.Error("expected failed status in body")
	}
}

func TestFormatPRBody_LongPlanTruncation(t *testing.T) {
	result := &engine.BuildResult{
		Plan:       strings.Repeat("x", 3000),
		Status:     engine.BuildStatusSuccess,
		Iterations: 1,
	}

	body := FormatPRBody(result)

	if !strings.Contains(body, "...plan truncated...") {
		t.Error("expected plan truncation marker")
	}
}

func TestCollectPrinciples(t *testing.T) {
	reviews := []review.Result{
		{PrinciplesCovered: []string{"sec-001", "arch-001"}},
		{PrinciplesCovered: []string{"sec-001", "perf-001"}},
	}

	got := collectPrinciples(reviews)
	if len(got) != 3 {
		t.Errorf("expected 3 unique principles, got %d: %v", len(got), got)
	}
}
