#!/usr/bin/env bash
# build-env.sh - generate deploy/.env from local secrets.
#
# Sources:
#   - ANTHROPIC_API_KEY: ~/.openclaw/agents/main/agent/auth-profiles.json
#     (profile "anthropic:default", type "api_key")
#   - DISCORD_BOT_TOKEN / DISCORD_GUILD_ID and friends:
#     ~/.openclaw/workspace/secrets/discord-bridge.env (operator-managed)
#
# Output: deploy/.env (consumed by docker compose --env-file)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEPLOY_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
OUT_FILE="${DEPLOY_DIR}/.env"

AUTH_PROFILES="${HOME}/.openclaw/agents/main/agent/auth-profiles.json"
DISCORD_SECRETS="${HOME}/.openclaw/workspace/secrets/discord-bridge.env"

err() { echo "error: $*" >&2; exit 1; }

[ -r "$AUTH_PROFILES" ] || err "auth-profiles.json not readable at $AUTH_PROFILES"
[ -r "$DISCORD_SECRETS" ] || err "discord secrets not readable at $DISCORD_SECRETS — create it with DISCORD_BOT_TOKEN and DISCORD_GUILD_ID"

# Extract the api_key from the first profile of type=api_key under anthropic.
# Supports two schemas:
#   Current (dict):  {"profiles": {"anthropic:default": {"provider":"anthropic","type":"api_key","key":"sk-..."}}}
#   Legacy  (list):  {"profiles": [{"provider":"anthropic","type":"api_key","apiKey":"sk-..."}]}
ANTHROPIC_API_KEY="$(python3 - "$AUTH_PROFILES" <<'PY'
import json, sys
with open(sys.argv[1]) as fh:
    data = json.load(fh)
profiles = data.get("profiles", {})

# Current schema: profiles is a dict keyed by profile id.
if isinstance(profiles, dict):
    for pid, p in profiles.items():
        if p.get("provider") != "anthropic":
            continue
        if p.get("type") == "api_key" and p.get("key"):
            print(p["key"])
            sys.exit(0)

# Legacy schema: profiles is a list of objects with apiKey field.
if isinstance(profiles, list):
    for p in profiles:
        if p.get("provider") != "anthropic":
            continue
        if p.get("type") == "api_key" and p.get("apiKey"):
            print(p["apiKey"])
            sys.exit(0)
        creds = p.get("credentials") or {}
        if creds.get("apiKey"):
            print(creds["apiKey"])
            sys.exit(0)

sys.exit("no anthropic api_key profile found in " + sys.argv[1])
PY
)"

[ -n "$ANTHROPIC_API_KEY" ] || err "anthropic api key extraction returned empty"

# Source discord secrets file (it sets DISCORD_BOT_TOKEN, DISCORD_GUILD_ID, etc).
# shellcheck disable=SC1090
set -a
. "$DISCORD_SECRETS"
set +a

: "${DISCORD_BOT_TOKEN:?missing DISCORD_BOT_TOKEN in $DISCORD_SECRETS}"
: "${DISCORD_GUILD_ID:?missing DISCORD_GUILD_ID in $DISCORD_SECRETS}"

umask 077
{
  echo "# Generated by deploy/scripts/build-env.sh — do not edit by hand."
  echo "ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}"
  echo "DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}"
  echo "DISCORD_GUILD_ID=${DISCORD_GUILD_ID}"
  [ -n "${BRIDGE_BOT_NAME:-}" ] && echo "BRIDGE_BOT_NAME=${BRIDGE_BOT_NAME}"
  [ -n "${BRIDGE_BOT_STATUS:-}" ] && echo "BRIDGE_BOT_STATUS=${BRIDGE_BOT_STATUS}"
  [ -n "${BRIDGE_LOG_LEVEL:-}" ] && echo "BRIDGE_LOG_LEVEL=${BRIDGE_LOG_LEVEL}"
  [ -n "${BRIDGE_SHOW_THINKING:-}" ] && echo "BRIDGE_SHOW_THINKING=${BRIDGE_SHOW_THINKING}"
  [ -n "${BRIDGE_REVEAL_SESSION_ID:-}" ] && echo "BRIDGE_REVEAL_SESSION_ID=${BRIDGE_REVEAL_SESSION_ID}"
  [ -n "${BRIDGE_ADMIN_TOKEN:-}" ] && echo "BRIDGE_ADMIN_TOKEN=${BRIDGE_ADMIN_TOKEN}"
  # FORGE_WORKSPACE_DIR is required by compose; default to forge repo if unset.
  echo "FORGE_WORKSPACE_DIR=${FORGE_WORKSPACE_DIR:-${HOME}/code/forge}"
} > "$OUT_FILE"

chmod 600 "$OUT_FILE"
echo "wrote $OUT_FILE"
